version: '3'

services:
  app:
    image: git.mamahaha.work/sangge/chatroom:latest
    command: uwsgi --ini config/uwsgi.ini
    volumes:
      - ./logs/uwsgilogs:/app/logs/uwsgilogs
      - ./instance:/app/instance
    expose:
      - "8000"
  
  nginx:
    image: git.mamahaha.work/sangge/chatnginx:latest
    ports:
      - "81:80"
    volumes:
      - ./logs/nginxlogs:/var/log/nginx
    depends_on:
      - app

  mariadb:
    image: mariadb:latest
    container_name: mariadb_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: flaskdb
      MYSQL_USER: flaskuser
      MYSQL_PASSWORD: flaskpassword
    expose:
      - "3306"
    volumes:
      - volumes:
      - E:\chatroom\instance:/var/lib/mysql

