version: '3'

services:
  app:
    image: git.mamahaha.work/sangge/chatroom:latest
    command: python /app/app.py
    volumes:
      - ./logs/uwsgilogs:/app/logs/uwsgilogs
      - ./instance:/app/instance
    expose:
      - "8000"
  
  nginx:
    image: git.mamahaha.work/sangge/chatnginx:latest
    ports:
      - "81:80"
    volumes:
      - ./logs/nginxlogs:/var/log/nginx
    depends_on:
      - app
