name: Deploy Chat Room

on:
  push:
    branches:
      - main

jobs:

  build:
    name: build image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3


    - name: Login to Gitea Container Registry
      uses: docker/login-action@v2
      with:
        registry: git.mamahaha.work
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      env:
        ACTIONS_RUNTIME_TOKEN: ''
      with:
        context: .
        push: true
        tags: git.mamahaha.work/sangge/chatroom:latest
