name: Deploy Chat Room

on:
  push:
    branches:
      - main

jobs:

  build:
    name: build image
    runs-on: debian
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Gitea Container Registry
      run: docker login your-gitea-registry-url -u ${{ secrets.USERNAME }} -p ${{ secrets.TOKEN }}


    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: sangge/chatroom:latest  # 更改为你的DockerHub用户名和镜像名称
