name: Deploy Chat Room

on:
  push:
    branches:
      - main

jobs:
  build:
    name: build image
    runs-on: ubuntu-latest

    container:
      image: catthehacker/ubuntu:act-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        driver: docker

    - name: Login to Gitea Container Registry
      uses: docker/login-action@v2
      with:
        registry: git.mamahaha.work
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.TOKEN }}

    - name: Build Docker image
      run: |
        export APP_VERSION=$(python -c "from config import APP_VERSION; print(APP_VERSION)")
        docker buildx build . -t git.mamahaha.work/sangge/chatroom:$APP_VERSION -f Dockerfile
        docker tag git.mamahaha.work/sangge/chatroom:$APP_VERSION git.mamahaha.work/sangge/chatroom:latest
        docker buildx build . -t git.mamahaha.work/sangge/chatnginx:$APP_VERSION -f Dockerfile
        docker tag git.mamahaha.work/sangge/chatnginx:$APP_VERSION git.mamahaha.work/sangge/chatnginx:latest
        

    - uses: actions/checkout@v3
    - name: copy file via ssh password
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "docker-compose.yml"
        target: E:\chatroom

    - name: Start Docker Compose
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
          cd E:\chatroom;docker compose up    