name: Deploy Chat Room

on:
  push:
    branches:
      - main

jobs:
  build:
    name: build image
    runs-on: ubuntu-latest

    container:
      image: catthehacker/ubuntu:act-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        driver: docker

    - name: Login to Gitea Container Registry
      uses: docker/login-action@v2
      with:
        registry: git.mamahaha.work
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.TOKEN }}

    - name: Build and push Docker image
      run: |
        export APP_VERSION=$(python -c "from config import APP_VERSION; print(APP_VERSION)")
        docker buildx build . -t git.mamahaha.work/sangge/chatroom:$APP_VERSION
        docker push git.mamahaha.work/sangge/chatroom:$APP_VERSION