name: Deploy Chat Room

on:
  push:
    branches:
      - main

jobs:

  build:
    name: build image
    runs-on: debian
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Gitea Container Registry
      uses: docker/login-action@v2
      with:
        registry: git.mamahaha.work
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: git.mamahaha.work/sangge/chatroom:latest  # 更改为你的DockerHub用户名和镜像名称
